### PR TITLE
Added part numbers to all the components.

### PR DESCRIPTION
**Pull request by filcarv**

### CODE REVIEW

**Comment by daharoni** [comment]
@filcarv, thanks for the PR. It looks like some of the fabrication specs were also changed here like drill diameters. Is that correct?

@fnsangiul, can you review this and merge the PR when you get a chance.

**Comment by filcarv** [comment]
@daharoni Yes, the fabricatio specs were slightly changed to meet with the current PCB manufacturers. Also to reduce the number of DRC errors. Nevertheless, the output gerbers don't have any difference.

**Comment by filcarv** [comment]
Hi, @daharoni and @fnsangiul 
Do you need any more information about this PO?
This is our final step before starting to work on the production.

**Comment by daharoni** [comment]
Sorry for the delay! @fnsangiul will review this today.

**Comment by fnsangiul** [comment]
Done! Everything looks good.

**Pull request merged**
